import test from 'node:test';
import assert from 'node:assert/strict';
import Database from 'better-sqlite3';
import express from 'express';
import session from 'express-session';
import {once} from 'node:events';
import type {AddressInfo} from 'node:net';
import {migrateChecklistDatabase} from '../src/checklists/migrations.js';
import {createTemplateService} from '../src/checklists/templates.js';
import {createShiftService} from '../src/checklists/shifts.js';
import {createRunService} from '../src/checklists/runs.js';
import {createRunRouter} from '../src/checklists/run-routes.js';
import {createAuthService} from '../src/auth.js';
import {scheduleFixture} from './fixtures/checklist-schedule.js';
import {templateFixture} from './fixtures/checklist-template.js';
async function fixture(t:any,failAudit=false){
 const db=new Database(':memory:'),journal=new Database(':memory:');db.pragma('foreign_keys=ON');migrateChecklistDatabase(db);
 journal.exec(`CREATE TABLE roles(name TEXT PRIMARY KEY,view_checklists INTEGER,create_checklists INTEGER,edit_own_checklists INTEGER,manage_checklists INTEGER);
 INSERT INTO roles VALUES('technician',1,1,1,0),('employee',1,0,0,0),('custom_manager',1,1,0,1);
 CREATE TABLE users(id INTEGER PRIMARY KEY,username TEXT,full_name TEXT,role TEXT,active INTEGER DEFAULT 1,deleted INTEGER DEFAULT 0);
 INSERT INTO users(id,username,full_name,role) VALUES(1,'tech','Texnik','technician'),(2,'employee','Employee','employee'),(3,'other','Other','technician'),(4,'manager','Manager','custom_manager');`);
 let instant=new Date('2026-09-19T00:00:00Z');const now=()=>instant;
 const templates=createTemplateService(db);let v=templates.create({code:'DAILY',name:'Daily'},1);
 const structure=structuredClone(templateFixture);structure.sections[0].items.push({stable_key:'OPTIONAL',name:'Optional',equipment_name:'Test',sort_order:10,required:false,active:true});
 v=templates.update(v.id,{...structure,revision:1});templates.publish(v.id,2,1);
 const shifts=createShiftService(db,now),s=shifts.create(scheduleFixture,1);shifts.publish(s.id,1,1);instant=new Date('2026-09-19T05:00:00Z');
 const app=express(),auth=createAuthService(journal,'test-only'),audit:any[]=[];app.use(express.json());app.use(session({secret:'test-only',resave:false,saveUninitialized:false}));
 app.use('/api',createRunRouter({available:true,db},auth,{write(e){if(failAudit)throw Error('audit failure');audit.push(e);}},now));
 app.use((e:unknown,_q:express.Request,s:express.Response,_n:express.NextFunction)=>s.status(500).json({error:String(e)}));
 const server=app.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));db.close();journal.close();});
 const call=async(url:string,method='GET',body?:unknown,user=1)=>{const r=await fetch(`http://127.0.0.1:${(server.address() as AddressInfo).port}/api`+url,{method,headers:{'Content-Type':'application/json','X-CNS-Token':auth.signAuthToken(user)},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,body:await r.json()};};
 const created=await call('/checklists','POST',{}),run=created.body.run;
 const sections=await Promise.all(run.sections.map(async(s:any)=>(await call(`/checklists/${run.id}/sections/${s.id}`)).body));
 return {db,audit,call,run,sections,set:(s:string)=>{instant=new Date(s);}};
}
test('execution acceptance, intermediate autosave, summary, completion, readonly and edit expiry',async t=>{
 const {call,run,sections,audit,set}=await fixture(t);const base='/checklists/'+run.id;
 const a=sections[0].items[0],optional=sections[0].items[1],b=sections[1].items[0];
 const update=(i:any,data:any,expectedRevision=1,user=1)=>call(`${base}/items/${i.id}`,'PATCH',{...data,expectedRevision},user);
 assert.equal((await update(a,{result:'ok'})).status,200);
 assert.equal((await update(a,{result:'problem'},2)).status,200);
 let result=await call(base+'/complete','POST',{});assert.equal(result.status,422);assert.ok(result.body.incompleteItems.some((i:any)=>i.id===a.id&&i.reason==='comment_required'));assert.ok(result.body.incompleteItems.some((i:any)=>i.id===b.id));
 assert.equal((await update(a,{comment:'SECRET_COMMENT'},3)).body.item.revision,4);
 const reread=await call(`${base}/sections/${sections[0].id}`);assert.equal(reread.body.items[0].comment,'SECRET_COMMENT');
 result=await call(base+'/complete','POST',{});assert.equal(result.status,422);assert.equal(result.body.incompleteItems.length,1);assert.equal(result.body.incompleteItems[0].id,b.id);
 assert.equal((await update(b,{result:'na'})).status,200);assert.equal((await call(base+'/complete','POST',{})).status,422);
 await update(b,{comment:'Moved'},2);result=await call(base);assert.deepEqual(result.body.progress,{completed_sections:2,total_sections:2,completed_required_items:2,total_required_items:2,ok_count:0,problem_count:1,na_count:1,unanswered_required_count:0});
 result=await call(base+'/complete','POST',{});assert.equal(result.status,200);assert.equal(result.body.run.status,'completed');const first=result.body.run.first_completed_at;
 assert.equal((await call(base+'/complete','POST',{})).body.run.revision,result.body.run.revision);
 set('2026-09-19T05:10:00Z');result=await update(a,{result:'ok'},4);assert.equal(result.body.run.status,'completed');assert.equal(result.body.run.first_completed_at,first);assert.notEqual(result.body.run.completed_at,first);
 result=await update(optional,{result:'problem'});assert.equal(result.body.run.status,'in_progress');assert.equal(result.body.run.completed_at,null);assert.equal(result.body.run.first_completed_at,first);
 assert.equal((await call(base+'/complete','POST',{})).status,422);
 await update(optional,{comment:'Optional issue'},2);assert.equal((await call(base+'/complete','POST',{})).body.run.first_completed_at,first);
 const employee=await call(base,'GET',undefined,2);assert.equal(employee.body.can_edit,false);assert.equal(employee.body.progress.ok_count,1);assert.equal(employee.body.progress.problem_count,1);assert.equal(employee.body.progress.na_count,1);
 assert.equal((await update(a,{result:'na'},5,2)).status,403);assert.equal((await call(base+'/complete','POST',{},2)).status,403);
 set('2026-09-19T16:00:00.001Z');assert.equal((await call(base)).body.can_edit,false);assert.equal((await update(a,{result:null},5)).status,403);assert.equal((await call(base+'/complete','POST',{})).status,403);
 assert.equal((await update(a,{result:null},5,4)).status,200);
 for(const event of ['CHECKLIST_ITEM_UPDATE','CHECKLIST_COMPLETE','CHECKLIST_EDIT_AFTER_COMPLETE','CHECKLIST_REOPEN','CHECKLIST_ADMIN_EDIT'])assert.ok(audit.some(e=>e.event===event&&e.result==='SUCCESS'),event);
 assert.ok(!JSON.stringify(audit).includes('SECRET_COMMENT'));const entry=audit.find(e=>e.event==='CHECKLIST_ITEM_UPDATE'&&e.result==='SUCCESS');assert.equal(entry.item_id,a.id);assert.equal(entry.section_id,sections[0].id);assert.equal(entry.revision,2);assert.equal(entry.changed_fields,'result');
});
test('membership, ownership, revisions, invalid values, section notes and deleted runs',async t=>{
 const {call,run,sections,db,audit}=await fixture(t);const base='/checklists/'+run.id,item=sections[0].items[0],sid=sections[0].id;
 assert.equal((await call(base+'/items/'+item.id,'PATCH',{expectedRevision:1,result:'unchecked'})).status,422);
 assert.equal((await call(base+'/items/'+item.id,'PATCH',{expectedRevision:1,result:'ok'},3)).status,403);
 const other=(await call('/checklists','POST',{is_extra:true,override_reason:'Membership test'},4)).body.run;const os=(await call(`/checklists/${other.id}/sections/${other.sections[0].id}`,'GET',undefined,4)).body;
 assert.equal((await call(base+'/items/'+os.items[0].id,'PATCH',{expectedRevision:1,result:'ok'})).status,404);
 assert.equal((await call(base+'/sections/'+os.id,'PATCH',{expectedRevision:1,section_comment:'bad'})).status,404);
 assert.equal((await call(base+'/sections/'+sid,'PATCH',{expectedRevision:1,section_comment:'PRIVATE_NOTE'})).body.section.revision,2);
 assert.equal((await call(base+'/sections/'+sid,'PATCH',{expectedRevision:1,section_comment:'overwrite'})).status,409);
 assert.equal((await call(base+'/sections/'+sid,'PATCH',{expectedRevision:2,section_comment:'reader'},2)).status,403);
 assert.equal((await call(base+'/items/'+item.id,'PATCH',{expectedRevision:1,result:'ok'})).body.item.revision,2);
 assert.equal((await call(base+'/items/'+item.id,'PATCH',{expectedRevision:1,result:'problem'})).status,409);
 assert.equal((await call(base+'/items/'+item.id,'PATCH',{expectedRevision:2,result:null})).body.item.result,null);
 assert.ok(audit.some(e=>e.event==='CHECKLIST_NOTE_UPDATE'&&e.result==='SUCCESS'));assert.ok(!JSON.stringify(audit).includes('PRIVATE_NOTE'));
 await call(base,'DELETE',{delete_reason:'test'},4);assert.equal((await call(base+'/items/'+item.id,'PATCH',{expectedRevision:3,result:'ok'},4)).status,403);
 assert.equal((db.prepare('SELECT result FROM checklist_run_items WHERE id=?').get(item.id) as any).result,null);
});
test('failed audit preserves a valid save and run status transition is atomic',async t=>{
 const {call,run,sections,db}=await fixture(t,true);const base='/checklists/'+run.id,item=sections[0].items[0];
 assert.equal((await call(base+'/items/'+item.id,'PATCH',{expectedRevision:1,result:'ok'})).status,200);
 db.exec("CREATE TRIGGER reject_run_update BEFORE UPDATE ON checklist_runs BEGIN SELECT RAISE(ABORT,'test rollback'); END");
 assert.equal((await call(base+'/items/'+item.id,'PATCH',{expectedRevision:2,result:'problem'})).status,500);
 const saved=db.prepare('SELECT result,revision FROM checklist_run_items WHERE id=?').get(item.id) as any;assert.equal(saved.result,'ok');assert.equal(saved.revision,2);
});
