import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import fs from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'/private/tmp/cns-browser-test/node_modules/playwright/index.mjs');
const child=spawn(process.execPath,['node_modules/tsx/dist/cli.mjs','test/fixtures/checklist-browser-server.ts'],{stdio:['ignore','pipe','inherit']});
let browser;
try {
 const [out]=await once(child.stdout,'data'),config=JSON.parse(out.toString()),base=`http://127.0.0.1:${config.port}`;
 browser=await chromium.launch({executablePath:process.env.CHROME_PATH??'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 const context=await browser.newContext({viewport:{width:1024,height:768}});await context.addInitScript(token=>localStorage.setItem('cns_auth_token',token),config.tech);
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(base);
 await page.locator('[data-tab="checklists"]').click();await page.getByRole('button',{name:'Yeni yoxlamaya başla',exact:true}).click();const root=page.locator('#tab-checklists');
 await page.locator('[data-result="problem"]').first().click();await page.waitForFunction(()=>document.querySelector('[data-save]')?.textContent==='Yadda saxlanıldı');await root.locator('[data-cl="next"]').click();assert.equal(await root.locator('.cl-nav-complete').getAttribute('data-ready'),'false','Problem without comment blocks completion');await root.locator('[data-cl="previous"]').click();
 await page.locator('[data-result="na"]').first().click();await page.waitForFunction(()=>document.querySelector('[data-save]')?.textContent==='Yadda saxlanıldı');await root.locator('[data-cl="next"]').click();assert.equal(await root.locator('.cl-nav-complete').getAttribute('data-ready'),'false','N/A without comment blocks completion');await root.locator('[data-cl="previous"]').click();
 await page.locator('[data-result="problem"]').first().click();await page.locator('[data-comment]').first().fill('Monitor korpusunda çat var');await page.locator('[data-comment]').first().blur();
 await page.waitForFunction(()=>document.querySelector('[data-save]')?.textContent==='Yadda saxlanıldı');await root.locator('[data-cl="next"]').click();
 assert.equal(await root.locator('[data-cl="next"]').count(),0,'last page has no disabled Next');assert.equal(await root.locator('.cl-nav-complete').textContent(),'✓ Yoxlamanı tamamla');assert.equal(await root.locator('.cl-nav-complete').getAttribute('data-ready'),'false');assert.equal(await root.locator('.cl-nav-complete').evaluate(e=>e.classList.contains('is-ready')),false);
 await fs.mkdir('/private/tmp/cns-final-ux',{recursive:true});await page.screenshot({path:'/private/tmp/cns-final-ux/complete-gray-1024.png',fullPage:true});
 await root.locator('[data-cl="complete"]').click();assert.equal(await root.locator('.cl-native-modal').isVisible(),true);await root.locator('[data-cl="complete-confirm"]').click();await root.locator('.cl-incomplete-list').waitFor();assert.match(await root.locator('.cl-native-modal').textContent(),/nəticə seçilməyib/);
 await root.locator('.cl-incomplete-section').first().evaluate(e=>e.textContent='HHİE əməliyyat zalı üzrə yoxlama — çox uzun mövqe adı');await root.locator('.cl-incomplete-item').first().evaluate(e=>e.textContent='SUP APP konsolu — Aircon CMD/FDD/SDD və NEC monitor avadanlığının tam texniki yoxlanılması');
 for(const [width,height,name] of [[390,844,'incomplete-390.png'],[393,852,null],[430,932,null],[768,1024,'incomplete-768.png'],[1024,768,'incomplete-1024.png']]){await page.setViewportSize({width,height});const modal=root.locator('.cl-native-modal'),list=root.locator('.cl-incomplete-list'),mb=await modal.boundingBox();assert.ok(mb&&mb.x>=0&&mb.x+mb.width<=width,`modal outside ${width}`);assert.equal(await list.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true,`incomplete list overflow ${width}`);assert.equal(await modal.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true,`modal overflow ${width}`);if(name)await page.screenshot({path:'/private/tmp/cns-final-ux/'+name,fullPage:true});}
 await root.locator('[data-cl="jump-incomplete"]').first().click();await root.locator('.cl-jump-highlight').waitFor();
 await root.locator('[data-result="ok"]').click();await page.waitForFunction(()=>document.querySelector('[data-save]')?.textContent==='Yadda saxlanıldı');
 await root.locator('[data-cl="previous"]').click();assert.equal(await root.locator('[data-comment]').inputValue(),'Monitor korpusunda çat var');
 await root.locator('[data-cl="next"]').click();assert.equal(await root.locator('.cl-nav-complete').getAttribute('data-ready'),'true');assert.equal(await root.locator('.cl-nav-complete').evaluate(e=>e.classList.contains('is-ready')),true);await page.screenshot({path:'/private/tmp/cns-final-ux/complete-green-1024.png',fullPage:true});await root.locator('[data-cl="complete"]').click();await root.locator('[data-cl="complete-confirm"]').click();await page.waitForFunction(()=>document.querySelector('[data-summary]')?.textContent.includes('Tamamlandı'));
 assert.match(await root.locator('[data-summary]').textContent(),/1 OK · 1 Problem · 0 N\/A/);
 await root.locator('[data-cl="list"]').click();await root.locator('.cl-list').waitFor();const completedContext=await(await context.request.get(base+'/api/checklists/context',{headers:{'X-CNS-Token':config.tech}})).json();assert.equal(await root.getByRole('button',{name:'Mövcud yoxlamanı redaktə et',exact:true}).count(),1,`completed editable owner CTA: ${JSON.stringify(completedContext)}`);await root.locator('[data-cl="open"]').first().click();
 await fs.mkdir('/private/tmp/cns-stage5-screenshots',{recursive:true});
 for(const width of [1366,1024,768]){const height=width===1024?768:width===768?1024:900;await page.setViewportSize({width,height});assert.equal(await page.locator('#login-screen').isVisible(),false);
 await root.evaluate(e=>{e.scrollTop=0;});
  assert.equal(await root.evaluate(e=>getComputedStyle(e).overflowY),'auto');
  const nav=await root.locator('.cl-position-nav').boundingBox();assert.ok(nav.y>=0&&nav.y+nav.height<=height,`navigation outside viewport at ${width}`);
  await page.screenshot({path:`/private/tmp/cns-stage5-screenshots/execution-${width}.png`,fullPage:true});
  const dimensions=await root.evaluate(e=>({scroll:e.scrollWidth,width:e.clientWidth}));assert.ok(dimensions.scroll<=dimensions.width+1,`horizontal overflow at ${width}`);
  for(const size of await root.locator('[data-result]').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().height)))assert.ok(size>=44);
  assert.match(await root.locator('.cl-tk').first().textContent(),/TK:/);const columns=await root.locator('.cl-items').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length);if(width===1024)assert.equal(columns,2,'landscape uses two columns');if(width===768)assert.equal(columns,1,'portrait uses one column');
 }
 for(const [width,height] of [[390,844],[393,852],[430,932],[844,390]]){await page.setViewportSize({width,height});const nav=await root.locator('.cl-position-nav').boundingBox(),metrics=await root.evaluate(e=>({scrollTop:e.scrollTop,scrollHeight:e.scrollHeight,clientHeight:e.clientHeight,overflow:getComputedStyle(e).overflowY}));assert.ok(nav&&nav.y>=0&&nav.y+nav.height<=height,`mobile navigation outside viewport ${width}x${height}: ${JSON.stringify({nav,metrics})}`);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1),true);assert.equal(await root.locator('.cl-results').first().evaluate(e=>getComputedStyle(e).flexDirection),'column');if(width<=600){const footer=page.locator('#app-screen .app-footer'),fb=await footer.boundingBox();assert.ok(fb&&fb.x>=0&&fb.x+fb.width<=width&&fb.y+fb.height<=height,`checklist footer outside ${width}x${height}`);assert.equal(await footer.evaluate(e=>getComputedStyle(e).flexDirection),'column');}if(width===390)await page.screenshot({path:'/private/tmp/cns-stage11-checklist-phone-390.png',fullPage:true});}
 await root.locator('[data-cl="navigator"]').click();assert.equal(await root.locator('.cl-nav-entry.is-complete').count(),2);assert.equal(await root.locator('.cl-nav-entry.is-current').count(),1);await root.locator('[data-cl="close-nav"]').click();
 // Network error keeps textarea value and offers explicit retry.
 await context.setOffline(true);await root.locator('[data-comment]').fill('Local value retained');await root.locator('[data-comment]').blur();
 await page.waitForFunction(()=>document.querySelector('[data-save]')?.textContent.startsWith('Saxlanılmadı'));assert.equal(await root.locator('[data-comment]').inputValue(),'Local value retained');
 page.removeAllListeners('dialog');let warned=false;page.once('dialog',d=>{warned=true;d.dismiss();});
 await root.locator('[data-cl="next"]').click();assert.equal(warned,true);assert.equal(await root.locator('[data-comment]').inputValue(),'Local value retained');page.on('dialog',d=>d.accept());
 assert.equal(await page.evaluate(()=>{const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented;}),true);
 await context.setOffline(false);await root.locator('[data-cl="retry"]').click();await page.waitForFunction(()=>document.querySelector('[data-save]')?.textContent==='Yadda saxlanıldı');
 // Real competing API update produces 409; no automatic overwrite.
 const rows=await (await context.request.get(base+'/api/checklists',{headers:{'X-CNS-Token':config.tech}})).json(),id=rows.rows[0].id;
 const r=await(await context.request.get(base+'/api/checklists/'+id,{headers:{'X-CNS-Token':config.tech}})).json();
 const s=await(await context.request.get(`${base}/api/checklists/${id}/sections/${r.sections[0].id}`,{headers:{'X-CNS-Token':config.tech}})).json();
 await context.request.patch(`${base}/api/checklists/${id}/items/${s.items[0].id}`,{headers:{'X-CNS-Token':config.tech},data:{expectedRevision:s.items[0].revision,comment:'Concurrent'}});
 await root.locator('[data-comment]').fill('Do not overwrite');await root.locator('[data-comment]').blur();await page.waitForFunction(()=>document.querySelector('[data-save]')?.textContent.includes('başqa yerdə'));
 assert.equal(await root.locator('[data-comment]').inputValue(),'Do not overwrite');assert.equal(await root.locator('[data-cl="retry"]').isVisible(),false);
 await root.locator('[data-cl="reload"]').click();await page.waitForFunction(()=>document.querySelector('[data-comment]')?.value==='Concurrent');
 // Admin gets explicit extra-run and soft-delete controls; normal users do not.
 assert.equal(await root.locator('[data-cl="delete"]').count(),0);
 const admin=await browser.newContext({viewport:{width:390,height:844}});await admin.addInitScript(token=>localStorage.setItem('cns_auth_token',token),config.admin);const ap=await admin.newPage();await ap.goto(base);await ap.locator('#mobile-menu-trigger').click();await ap.locator('[data-tab="checklists"]').click();const ar=ap.locator('#tab-checklists');await ar.locator('.cl-list').waitFor();assert.equal(await ar.locator('[data-cl="extra"]').count(),1,'admin extra button');
 await ar.locator('[data-cl="extra"]').click();await ar.locator('[data-extra-reason]').fill('Şablon yoxlaması');await ar.locator('[data-cl="extra-confirm"]').click();await ar.locator('[data-cl="list"]').click();await ar.locator('.cl-list').waitFor();assert.ok(await ar.locator('.cl-extra').count()>=1,'first extra badge');
 await ar.locator('[data-cl="extra"]').click();await ar.locator('[data-cl="extra-confirm"]').click();await ar.locator('[data-cl="list"]').click();await ar.locator('.cl-list').waitFor();assert.ok(await ar.locator('.cl-extra').count()>=2,'second extra badge');
 const compactTime=ar.locator('.cl-history-time').first();assert.match(await compactTime.textContent(),/^\d{2}:\d{2} → (\d{2}:\d{2}|Davam edir)$/);assert.equal(await compactTime.locator('span').count(),1);const heightDelta=await compactTime.evaluate(time=>{const before=time.getBoundingClientRect().height,display=time.style.display,gap=time.style.gap,extra=document.createElement('span');extra.textContent='20.09.26, 23:15';time.style.display='grid';time.style.gap='4px';time.append(extra);const old=time.getBoundingClientRect().height;extra.remove();time.style.display=display;time.style.gap=gap;return Math.round(old-before);});assert.ok(heightDelta>0);await ap.screenshot({path:'/private/tmp/cns-stage5-screenshots/history-390-compact-time.png',fullPage:true});
 for(let n=0;n<28;n++){const response=await admin.request.post(base+'/api/checklists',{headers:{'X-CNS-Token':config.admin},data:{is_extra:true,override_reason:`Pagination fixture ${n+1}`}});assert.equal(response.status(),201);}await ap.evaluate(()=>window.CNSChecklists.open());await ar.locator('.cl-list').waitFor();assert.equal(await ar.locator('.cl-history-row').count(),4);assert.equal(await ar.locator('[data-cl="page-next"]').isEnabled(),true);assert.match(await ar.locator('.cl-pager span').textContent(),/Səhifə 1 \/ 8/);await ar.locator('[data-cl="page-next"]').click();assert.match(await ar.locator('.cl-pager span').textContent(),/Səhifə 2 \/ 8/);assert.equal(await ar.locator('[data-cl="page-prev"]').isEnabled(),true);await ar.locator('[data-cl="page-prev"]').click();
 const del=ar.locator('[data-cl="delete"]').first();await del.scrollIntoViewIfNeeded();assert.equal(await del.isVisible(),true,'admin delete button');await del.click();await ar.locator('[data-cl="delete-confirm"]').click();assert.match(await ar.locator('[data-modal-error]').textContent(),/səbəbini/);await ar.locator('[data-delete-reason]').fill('Test məlumatının təmizlənməsi');await ar.locator('[data-cl="delete-confirm"]').click();await ar.locator('.cl-native-modal').waitFor({state:'detached'});await admin.close();
 // Expired owner: no editable controls; direct API also rejects.
 await context.request.post(base+'/test-expire');await root.locator('[data-cl="list"]').click();await root.locator('[data-cl="open"]').first().click();assert.equal(await root.locator('[data-result]').count(),0);
 assert.equal((await context.request.patch(`${base}/api/checklists/${id}/items/${s.items[0].id}`,{headers:{'X-CNS-Token':config.tech},data:{expectedRevision:99,result:'ok'}})).status(),403);
 const employee=await browser.newContext({viewport:{width:768,height:1024}});await employee.addInitScript(token=>localStorage.setItem('cns_auth_token',token),config.employee);const ep=await employee.newPage();await ep.goto(base);await ep.locator('[data-tab="checklists"]').click();assert.equal(await ep.locator('[data-cl="create"]').count(),0);assert.equal(await ep.locator('[data-cl="delete"]').count(),0);await ep.screenshot({path:'/private/tmp/cns-stage5-screenshots/list-768.png',fullPage:true});assert.ok(await ep.locator('.cl-history-row').count()>0);assert.ok(await ep.locator('[data-cl="open"]',{hasText:'Bax'}).count()>0);await ep.screenshot({path:'/private/tmp/cns-stage5-screenshots/employee-readonly.png',fullPage:true});
 const other=await browser.newContext({viewport:{width:1024,height:768}});await other.addInitScript(token=>localStorage.setItem('cns_auth_token',token),config.othertech);const op=await other.newPage();await op.goto(base);await op.locator('[data-tab="checklists"]').click();assert.equal(await op.getByText(/Mövcud yoxlamaya davam et|Mövcud yoxlamanı redaktə et/).count(),0,'non-owner never gets top CTA');assert.equal(await op.locator('.cl-history-row [data-cl="open"]',{hasText:'Bax'}).count()>0,true);await other.close();
 assert.deepEqual(errors,[]);console.log(`PASS: browser acceptance, compact time saves ${heightDelta}px per mobile row; 1366/1024/768 and 390/393/430, navigation, offline retry, conflict, employee readonly.`);
} finally {await browser?.close();child.kill('SIGTERM');}
